namespace nav
    enum Action
        push = "push"
        pop = "pop"
    end enum

    enum ViewId
        home = "HomeView"
        movies = "MoviesView"
        games = "GamesView"
        movieDetails = "MovieDetailsView"
        multiview = "MultiviewView"
        mosaicPlayer = "MosaicPlayerView"
    end enum

    interface Request
        action as nav.Action
        optional view as nav.ViewId
        optional params as object
    end interface
end namespace


