import "pkg:/source/navigation/nav.interface.bs"
import "pkg:/source/navigation/viewNav.bs"

sub viewDidLoad(params as object)
end sub

sub viewWillAppear()
end sub

sub viewWillHide()
end sub

sub viewWillDisappear()
end sub

function setViewFocus() as boolean
    return m.top.setFocus(true)
end function

sub pushView(viewName as nav.ViewId, params as object)
    viewNav.pushView(m.top, viewName, params)
end sub

sub popView()
    viewNav.popView(m.top)
end sub

sub pushMovieDetails(movieRows as object)
    viewNav.pushMovieDetails(m.top, movieRows)
end sub
