import "pkg:/source/utils/logger.bs"
import "pkg:/source/services/analytics.bs"

sub init()
    m.top.functionName = "runLoop"
    m.top.control = "RUN"
end sub

sub runLoop()
    port = CreateObject("roMessagePort")
    m.top.observeField("event", port)

    while true
        msg = wait(0, port)

        if type(msg) = "roSGNodeEvent" and msg.GetField() = "event"
            analytics.sendEvent(msg.GetData())
        end if
    end while
end sub
