#!/usr/bin/env node
'use strict'

// Generates source/generated/localConfig.bs from bsconfig.local.json so that
// machine-specific addresses stay out of git. Run automatically by the
// prebuild/pretest npm hooks -- see package.json.

const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const CONFIG_PATH = path.join(ROOT, 'bsconfig.local.json')
const OUT_PATH = path.join(ROOT, 'source', 'generated', 'localConfig.bs')

function readLocalConfig() {
    try {
        return JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'))
    } catch (error) {
        if (error.code === 'ENOENT') {
            console.warn('[genLocalConfig] no bsconfig.local.json -- generating empty values')
        } else {
            console.warn(`[genLocalConfig] bsconfig.local.json unreadable (${error.message}) -- generating empty values`)
        }
        return {}
    }
}

function brightScriptString(value) {
    const text = String(value == null ? '' : value).trim()

    if (text.includes('"')) {
        throw new Error(`[genLocalConfig] value contains a double quote, which BrightScript cannot escape: ${text}`)
    }

    return `"${text}"`
}

const config = readLocalConfig()

const contents = [
    "' AUTO-GENERATED by scripts/genLocalConfig.js -- do not edit, do not commit.",
    "' Values come from bsconfig.local.json, which is gitignored.",
    '',
    'namespace localConfig',
    '',
    '    function multiviewHost() as string',
    `        return ${brightScriptString(config.multiviewHost)}`,
    '    end function',
    '',
    'end namespace',
    ''
].join('\n')

const existing = fs.existsSync(OUT_PATH) ? fs.readFileSync(OUT_PATH, 'utf8') : null

if (existing === contents) {
    console.log('[genLocalConfig] source/generated/localConfig.bs already up to date')
} else {
    fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true })
    fs.writeFileSync(OUT_PATH, contents)
    console.log(`[genLocalConfig] wrote source/generated/localConfig.bs (multiviewHost=${config.multiviewHost || '<empty>'})`)
}
